[package]
name = "opsd"
version = "0.2.1"
edition = "2024"
rust-version = "1.86"
description = "Rust client library for the Opsd API"
homepage = "https://opsd.sh"
repository = "https://github.com/opsd-sh/opsd-rust"
documentation = "https://docs.rs/opsd"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["opsd", "api", "client", "sdk"]
categories = ["api-bindings", "web-programming::http-client"]
publish = ["crates-io"]

[features]
default = ["client"]
client = ["dep:reqwest", "dep:serde_json", "dep:thiserror", "dep:url"]

[dependencies]
reqwest = { version = "0.12.24", default-features = false, features = [
  "json",
  "rustls-tls",
], optional = true }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145", optional = true }
thiserror = { version = "2.0.17", optional = true }
time = { version = "0.3.45", features = ["serde", "parsing", "formatting"] }
url = { version = "2.5.7", optional = true }
uuid = { version = "1.26.0", features = ["serde"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
